# In this example, lint-format is a job among many others in a bigger GitHub workflow.
# This job has 3 steps: Checking out the code, running the lint command, and running the formatting command.
name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install
        
      - name: Run lint
        run: |
          yarn lint

  build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node: [18]
      needs: [lint-check]
      steps:
        - name: Checkout Commit
          uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node }}
        - name: Run build
          run: |
            yarn build